# Generated by Django 5.1 on 2024-08-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_ingredients_userrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
