# Generated by Django 5.1 on 2024-09-07 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_user_alter_userrecipe_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrecipe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userrecipe',
            unique_together={('recipe', 'user')},
        ),
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
    ]
